// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';

import 'pages/home/serialPage.dart';
import 'pages/indexPage.dart';
import 'pages/loginPage.dart';
import 'pages/playerPage.dart';
import 'pages/search/searchPage.dart';
import 'pages/search/searchResultPage.dart';
import 'pages/splashPage.dart';

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case "/loginPage":
      return RouteResult(
        widget: LoginPage(),
        showStatusBar: false,
        routeName: "loginPage",
      );
    case "/playerPage":
      return RouteResult(
        widget: PlayerPage(
          link: arguments['link'],
        ),
        showStatusBar: false,
        routeName: "playerPage",
      );
    case "/searchPage":
      return RouteResult(
        widget: SearchPage(),
        showStatusBar: false,
        routeName: "searchPage",
        pageRouteType: PageRouteType.transparent,
      );
    case "/searchResultPage":
      return RouteResult(
        widget: SearchResultPage(
          keyword: arguments['keyword'],
        ),
        showStatusBar: false,
        routeName: "searchResultPage",
        pageRouteType: PageRouteType.transparent,
      );
    case "/serialPage":
      return RouteResult(
        widget: SerialPage(
          link: arguments['link'],
          title: arguments['title'],
        ),
        showStatusBar: false,
        routeName: "serialPage",
      );
    case "app5dm://homePage":
      return RouteResult(
        widget: IndexPage(),
        showStatusBar: false,
        routeName: "homePage",
      );
    case "app5dm://splashPage":
      return RouteResult(
        widget: SplashPage(),
        showStatusBar: false,
        routeName: "splashPage",
        pageRouteType: PageRouteType.transparent,
      );
    default:
      return RouteResult();
  }
}

class RouteResult {
  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  const RouteResult({
    this.widget,
    this.showStatusBar = true,
    this.routeName = '',
    this.pageRouteType,
    this.description = '',
  });
}

enum PageRouteType { material, cupertino, transparent }

class Routes {
  const Routes._();

  /// loginPage
  ///
  /// [name] : /loginPage
  /// [routeName] : loginPage
  /// [showStatusBar] : false
  static const String LOGINPAGE = "/loginPage";

  /// playerPage
  ///
  /// [name] : /playerPage
  /// [routeName] : playerPage
  /// [arguments] : [link]
  /// [showStatusBar] : false
  static const String PLAYERPAGE = "/playerPage";

  /// searchPage
  ///
  /// [name] : /searchPage
  /// [routeName] : searchPage
  /// [showStatusBar] : false
  /// [pageRouteType] : PageRouteType.transparent
  static const String SEARCHPAGE = "/searchPage";

  /// searchResultPage
  ///
  /// [name] : /searchResultPage
  /// [routeName] : searchResultPage
  /// [arguments] : [keyword]
  /// [showStatusBar] : false
  /// [pageRouteType] : PageRouteType.transparent
  static const String SEARCHRESULTPAGE = "/searchResultPage";

  /// serialPage
  ///
  /// [name] : /serialPage
  /// [routeName] : serialPage
  /// [arguments] : [link, title]
  /// [showStatusBar] : false
  static const String SERIALPAGE = "/serialPage";

  /// homePage
  ///
  /// [name] : app5dm://homePage
  /// [routeName] : homePage
  /// [showStatusBar] : false
  static const String APP5DM_HOMEPAGE = "app5dm://homePage";

  /// splashPage
  ///
  /// [name] : app5dm://splashPage
  /// [routeName] : splashPage
  /// [showStatusBar] : false
  /// [pageRouteType] : PageRouteType.transparent
  static const String APP5DM_SPLASHPAGE = "app5dm://splashPage";
}
