// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';

import 'pages/indexPage.dart';
import 'pages/playerPage.dart';
import 'pages/splashPage.dart';

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case "/playerPage":
      return RouteResult(
        widget: PlayerPage(
          link: arguments['link'],
        ),
        showStatusBar: false,
        routeName: "playerPage",
      );
    case "app5dm://homePage":
      return RouteResult(
        widget: IndexPage(),
        showStatusBar: false,
        routeName: "homePage",
      );
    case "app5dm://splashPage":
      return RouteResult(
        widget: SplashPage(),
        showStatusBar: false,
        routeName: "splashPage",
        pageRouteType: PageRouteType.transparent,
      );
    default:
      return RouteResult();
  }
}

class RouteResult {
  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  const RouteResult({
    this.widget,
    this.showStatusBar = true,
    this.routeName = '',
    this.pageRouteType,
    this.description = '',
  });
}

enum PageRouteType { material, cupertino, transparent }

class Routes {
  const Routes._();

  /// playerPage
  ///
  /// [name] : /playerPage
  /// [routeName] : playerPage
  /// [arguments] : [link]
  /// [showStatusBar] : false
  static const String PLAYERPAGE = "/playerPage";

  /// homePage
  ///
  /// [name] : app5dm://homePage
  /// [routeName] : homePage
  /// [showStatusBar] : false
  static const String APP5DM_HOMEPAGE = "app5dm://homePage";

  /// splashPage
  ///
  /// [name] : app5dm://splashPage
  /// [routeName] : splashPage
  /// [showStatusBar] : false
  /// [pageRouteType] : PageRouteType.transparent
  static const String APP5DM_SPLASHPAGE = "app5dm://splashPage";
}
