
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by c
// **************************************************************************

class Images {
  static String cat = '/assets/images/cat.jpeg';
	static String iconCat = '/assets/images/icon/cat.jpeg';
	static String iconCat3x = '/assets/images/icon/cat@3x.jpeg';
	static String loading = '/assets/images/loading.gif';
	static String logo = '/assets/images/logo.png';
	
}
